### ISSUE TITLE
Weird 1.19 issue.

### ISSUE THREAD

**Issue by Tomhoran628** [EvModder/DropHeads#67]
Whenever i say type in chat it kicks me and then doesnt allow me to reconnect. Was able to narrow it down to DropHeads causing the issue by elimination. I have attached the message i get when i get kicked
![dropheads](https://user-images.githubusercontent.com/100648505/173271682-bfba5d3c-f5a5-457a-81ca-3298d620e8de.png)
.

**Comment by EvModder** [comment]
This is really strange; I see you marked it as closed so I'm guessing/hoping it is fixed in the latest version of DropHeads?

**Comment by Tomhoran628** [comment]
Unfortunately I think I prematurely marked it as closed. Still having the issue.

**Comment by Tomhoran628** [comment]
Unfortunately I'm still having the issue and prematurley closed it

**Comment by Tomhoran628** [comment]
Will do as soon as I get home from work! Thanks for the quick response. 10/10 plugin and 10/10 dev

**Comment by Al3xBogo** [comment]
I had the same issue whenever somebody typed a chat message or ran a command. The v3.7.5 jar fixed it (players don't get kicked) but it still shows this message in the console whenever a command/chat message is sent:

[12:37:44 WARN]: [DropHeads] Unable to parse json chat packet (in death message intercepter)

I have tested the latest version of Paper and Purpur on 1.19 with no other plugins and am still getting that message in the console.

**Comment by EvModder** [comment]
Can you send me your `DropHeads/config.yml` and `EssentialsX/config.yml` so I can try to recreate the issue on my end?

**Comment by EvModder** [comment]
Update: Actually I was able to get it to happen for me for player commands, and I figured out why.
I put that warning message in there to debug it, but the warning isn't really necessary so I will go ahead and remove it and update the jar

**Comment by Tomhoran628** [comment]
Awesome!

**Comment by EvModder** [comment]
I added it to the existing; sorry I didn't see this notification for your reply. The updated jar on Bukkit.org also has the fix so I think it should be safe for me to close this issue -- feel free to reopen if it still happens after updating
